### ISSUE TITLE
How often does this update itself?

### ISSUE THREAD

**Issue by JJ** [ugexe/Perl6-ecosystems#1]
It said every two hours, then once a day, then again every (roughly) two hours, but it's apparently updating itself once a day.

**Comment by ugexe** [comment]
see the README

**Comment by JJ** [comment]
![two long hours](https://user-images.githubusercontent.com/500/53698855-68b36000-3de2-11e9-87ed-2bf6f8ec28c5.png)
No it does not. They are two long hours.

**Comment by ugexe** [comment]
Did it occur to you that changes could occur in one ecosystem and not in the other?

**Comment by JJ** [comment]
So it's updated _only_ if there have been changes in the last two hours? And there have been no changes in the last 10 or 14 hours?
